


const link=
[
"https://drive.google.com/file/d/1sz67YnwYD8eA4SGKVWjxXz7YoefipleW/view?usp=drive_link",
" https://drive.google.com/file/d/1yImFhApK0sIoryy63skWoeF0R4tSknb-/view?usp=drive_link", 
"https://drive.google.com/file/d/1e_B9DF_5feCRl5tdhzoEixwUNCceaCvw/view?usp=drive_link",
" https://drive.google.com/file/d/1sj0Y42EbXAYFEir0eQkJpb7fLijcZ3jb/view?usp=drive_link",
" https://drive.google.com/file/d/1MlHIDAlSxwwbHsJ5CIYToxzzcZfHXf9U/view?usp=drive_link",
" https://drive.google.com/file/d/1hLge-i_BzokWhzGc4yfzxa6TE6U-GpGu/view?usp=drive_link",
" https://drive.google.com/file/d/1g7ezooKlfdjpnOPfGHjDY7tDeMW4Cxhw/view?usp=drive_link",
" https://drive.google.com/file/d/13xXJ5Tm3x6iuuEhrBohxFVsVRmgjLFgN/view?usp=drive_link",
 "https://drive.google.com/file/d/1Av4t5larH_KfjjaoJWT8YFd-lMPeyvqE/view?usp=drive_link",
 "https://drive.google.com/file/d/1LKUxebTC6IRH9TNKQcwp_L_L78f9Oz5z/view?usp=drive_link",
 "https://drive.google.com/file/d/13x8PwztTe_PmH9Ka2gr92pCzQFIpYXRy/view?usp=drive_link",
 "https://drive.google.com/file/d/1jU_3ont4Xr0VnHvQl2BRWfruWH9fQUTj/view?usp=drive_link",
 "https://drive.google.com/file/d/1eGBXEsazC3XI3z3n7ua8Ew6UQb1ih98j/view?usp=drive_link",
 "https://drive.google.com/file/d/13jmj5W0QGVtE9huIB2HPjqvOSwTa0IE-/view?usp=drive_link",
 "https://drive.google.com/file/d/1y0Evd_fh_o7iRYF4q4KJ-n_GClcW6whc/view?usp=drive_link",
 " https://drive.google.com/file/d/1-VbEXj86oeSUc7we9Mxjjqp80tL6CkHG/view?usp=drive_link",
 
 "https://drive.google.com/file/d/1_DUjZUrhtCr_3qHlYW2BEenJp_mdUUz2/view?usp=drive_link",
 "https://drive.google.com/file/d/1Zsap9r-ylpQk8nBkYHY62tLIxITOnwa-/view?usp=drive_link",
 "https://drive.google.com/file/d/1L9uu_ZG7gaiOJ-XNUkqXu0UmWXFhvj7e/view?usp=drive_link",
 "https://drive.google.com/file/d/1P2SDPoNqcR6TO4N-xm4i3922RMQ7AGCZ/view?usp=drive_link",
 "https://drive.google.com/file/d/1nclkPQ_NVd7Qr76nhdA-hvPOU53INnga/view?usp=drive_link",
 "https://drive.google.com/file/d/1nU5zZG8y_Q56k1OjOJlXpqYZI2Kqul32/view?usp=drive_link",
 "https://drive.google.com/file/d/1Rec1h3x8lLVht31fhbpyxYFgaM4ENAMG/view?usp=drive_link",
 " https://drive.google.com/file/d/1LEOZka_-xXwbWM_KbwxNuO9qkj57dfL7/view?usp=drive_link",
 "https://drive.google.com/file/d/1DUmmQXtHkbgmwbsEd223e4ScS407w-sG/view?usp=drive_link",
 "https://drive.google.com/file/d/1eMXKbKLbtQft2rZpl6t7kWAldFuB58nk/view?usp=drive_link",
 "https://drive.google.com/file/d/1fWWRP0GT63EuzdYu9XqLPE-KklsRgKD2/view?usp=drive_link",
 "https://drive.google.com/file/d/1nZRLSlyZgHR9nOq9Ws2uD-oeD2-uAhO7/view?usp=drive_link",
  "https://drive.google.com/file/d/1PwbIAkvDC-KA2P_1tNd3SxJfW8JLwXpE/view?usp=drive_link",
  "https://drive.google.com/file/d/1rHuG8grdAueKS--pVlXZTTy35kcjL363/view?usp=drive_link",
  "https://drive.google.com/file/d/1csWIXBih8L7lygPZ9cbj6jUhqCwiVCp5/view?usp=drive_link",
  "https://drive.google.com/file/d/1U1REZggP78UZ1ZunyxclJC6kKb2DMqgs/view?usp=drive_link",
  "https://drive.google.com/file/d/1HF2F5_TzsfZsAJtMPBu3PbctoxwZFh4O/view?usp=drive_link",
  "https://drive.google.com/file/d/1eQJFcjMyQ5omfrV-Ubz6XkvbTFH6nFWB/view?usp=drive_link",
  "https://drive.google.com/file/d/1pP8QKx3N1u1Kv-7dkpfLUnylcDlrVz1i/view?usp=drive_link",
  "https://drive.google.com/file/d/1atJ-8Lw0jqrZD6ZL0EONkaTnFl_mT2Jq/view?usp=drive_link",
  " https://drive.google.com/file/d/1Eeormiuog_AGRFyjoNjRHXmkGa9tJ-jw/view?usp=drive_link",
  "https://drive.google.com/file/d/1IXu9Or-t0lZv9Mtvud_UETZyvjixu0gi/view?usp=drive_link",
  " https://drive.google.com/file/d/1VxUja2iclP3swrlAUQz7oMutbmxDYJAN/view?usp=drive_link",
  "https://drive.google.com/file/d/1yWd-tZZYsEJ52YetEUIkZ1nfTYD1XDgh/view?usp=drive_link",
  "https://drive.google.com/file/d/1C2JsEJgYqkbglivy5ve30oDl7n2C95rO/view?usp=drive_link",
  "https://drive.google.com/file/d/1fWVMb1SInYe-o6WwfRlCiDc71Ot2v3bh/view?usp=drive_link",
  " https://drive.google.com/file/d/1rpZPooH6DTsaVGk0Y8XRJ0onLCSm83Zo/view?usp=drive_link",
  " https://drive.google.com/file/d/1PA20EyXLlyNrfOxbFS5L4q9gnWQJqupI/view?usp=drive_link",
  " https://drive.google.com/file/d/1mkrATdHPaabfcRJ_JDD8yekrjDJilWCX/view?usp=drive_link",
  " https://drive.google.com/file/d/1HQ88Zd-jJr5I5rcIt-OO8Gr8weUTdjaB/view?usp=drive_link",
  "https://drive.google.com/file/d/1Eeys7TCESZi7eRo-AXwQIYLLSRAfOQXr/view?usp=drive_link",
  " https://drive.google.com/file/d/1DvQ9zRQjHiYma1k2VCaA2cA5QZJXkoG9/view?usp=drive_link",
  " https://drive.google.com/file/d/1JlElQgI_9C8ZlW7DFFilaZm9vanCfMVc/view?usp=drive_link",
  " https://drive.google.com/file/d/1qKQ5-WvH6NTBMaq5Pv8atA46vIoQ87wQ/view?usp=drive_link",
  " https://drive.google.com/file/d/1_fHZHL7DqLRQ3WZxWT2p5wVUAPB2csbA/view?usp=drive_link",
  " https://drive.google.com/file/d/1eMWNJXEPV4fKf8EGv85xAdbB0oGzso9F/view?usp=drive_link",
  " https://drive.google.com/file/d/1wJ-p1kL5qatVY8ybUds73vML9jIkmHRf/view?usp=drive_link",
  " https://drive.google.com/file/d/1f-1TGVxMmDawhkiGciromk1d-IANI2B7/view?usp=drive_link",
  " https://drive.google.com/file/d/1Aa72X6VzjfP5G_QYuu81YXqUj6PWTnpU/view?usp=drive_link",
  " https://drive.google.com/file/d/1xcO0vVrWBNXkei_TWvCLMMMl81Hi2qT3/view?usp=drive_link",
  " https://drive.google.com/file/d/1kKFea8C5h26rqmY6aU9FVx3RSyc6MvtH/view?usp=drive_link",
  " https://drive.google.com/file/d/1SphGuvhnFqxbxzMGSjz4aD2NF-gk9xE9/view?usp=drive_link",
  " https://drive.google.com/file/d/1CCRsIyoIxCu3pmxjHwEr6AJg86uhR4yM/view?usp=drive_link",
  " https://drive.google.com/file/d/10ttkLJHZTEf1Lj4qSu-3XdUOHiWuKrTR/view?usp=drive_link",
  " https://drive.google.com/file/d/1ZJJIHoO4Hh9s8PXGvjysQB9jAghpXL7b/view?usp=drive_link",
  " https://drive.google.com/file/d/1Z_obH6DZAK8UkItsO1nnnWBWdTefk6s5/view?usp=drive_link",
  " https://drive.google.com/file/d/1ih5H4sZ-ttPIR3mmfzlLlSQYKnlfTNOQ/view?usp=drive_link",
  " https://drive.google.com/file/d/19M7irHP7T6lIScbIpIa4Jxh1nGckhC7B/view?usp=drive_link",


  " https://drive.google.com/file/d/1mG4BccCo1tLnuXtMzLqhG6f5hGWXSVru/view?usp=drive_link",
  " https://drive.google.com/file/d/1F9Gve_VVicJYytncaRXein7cdexnHzZR/view?usp=drive_link",
  " https://drive.google.com/file/d/1PLMjMm70qoRO0zqhaCl065mjLWUsTtQU/view?usp=drive_link",
  " https://drive.google.com/file/d/1NOyCaZ4SV-ZX_C0vCKM-yMXpyY6PtXNS/view?usp=drive_link",
  " https://drive.google.com/file/d/1aqdp_5c-kbvmbR4D5LK5WdORTBPPrPaQ/view?usp=drive_link",
  " https://drive.google.com/file/d/1SpGBlZid3_2Bk3ztqOiTqRXaL4jRLxWI/view?usp=drive_link",
  " https://drive.google.com/file/d/1cafbpdNiibFh3CfZrhARGj2H7q6XQSHn/view?usp=drive_link",
  "https://drive.google.com/file/d/1cyrYZHj8w-FYZBBuSAnq0QQdYGYVIZrY/view?usp=drive_link",
  " https://drive.google.com/file/d/1CfqoG3eiIBdDiIp-ETFUQUyeU8pDugV-/view?usp=drive_link",
  "https://drive.google.com/file/d/1r7yx21IoHv5VSUIQtd4qx-ExlGrI1Itm/view?usp=drive_link",
  " https://drive.google.com/file/d/1hG_HYBeO84N0SN0j94JJHoVa4d3TudTT/view?usp=drive_link",
  " https://drive.google.com/file/d/1EjtidDyjN0QHi7vnmHbYOTnHJiupk6_p/view?usp=drive_link",
  " https://drive.google.com/file/d/1AqXJhs1wdeorsAVvUSh6awKQz_6qIWad/view?usp=drive_link",
  " https://drive.google.com/file/d/1qhlpEAN1dcxfzlNXOpYhTH8xko--46g5/view?usp=drive_link",
  " https://drive.google.com/file/d/1MHzZI1zF_OwPJxhARJu5QJho2y18-5xu/view?usp=drive_link",
  " https://drive.google.com/file/d/1U2AA6WRf_hw0THy7myJ6ncx16cBglWAp/view?usp=drive_link",
  " https://drive.google.com/file/d/1CJVXAL5tmxRUYcsO0C8QevRlhzt2dhQw/view?usp=drive_link",
  " https://drive.google.com/file/d/1UxX18H-KNrG3qnEhp7K-RZOI_GKdr9pg/view?usp=drive_link",
  " https://drive.google.com/file/d/1nO6i69RkadRQ9pGHIuBGH16SgxmUtJQe/view?usp=drive_link",
  " https://drive.google.com/file/d/1lvDPCA8WLPoh3CNCpo4UOTg6nyIe96Xc/view?usp=drive_link",
  " https://drive.google.com/file/d/1DjEmOcKpJGma-WaAN9qjere_hlpzsUk-/view?usp=drive_link",
  "https://drive.google.com/file/d/1IU_m23vql4v4ykwkHtSyMXiSQt_6qNHe/view?usp=drive_link",
  " https://drive.google.com/file/d/181j1XEktyqs7Yo4PMXl48ReJChPC1YNH/view?usp=drive_link",
  " https://drive.google.com/file/d/1N-Y-wkhB2nsFVM4gg8UV5oV1AD7blwO4/view?usp=drive_link",
  " https://drive.google.com/file/d/1oC80FRzzhUW2DMevqW-r9JxwtdFqhmJu/view?usp=drive_link",
  " https://drive.google.com/file/d/1ZbaE7Nu_qTRQvkdz7M71cB2wXt0bISTN/view?usp=drive_link",
  " https://drive.google.com/file/d/1Ms7jAB-pOzYNvFsvJhN_ZbY2GTK5yNmU/view?usp=drive_link",
  " https://drive.google.com/file/d/1CN54BWTSwtkmZRvnqFCJkPTqbnIwckbT/view?usp=drive_link",
  " https://drive.google.com/file/d/1e-GIiDEiAcVWmt2kLIBbF6ZIm0-YHlBU/view?usp=drive_link",
  " https://drive.google.com/file/d/1TFSZfr_VjqZzI3sK9qi66g6HcLEl2DPx/view?usp=drive_link",
  "https://drive.google.com/file/d/1j7knYWmS_PCeb3XTYoHLiSJgBca9RoEV/view?usp=drive_link",
  " https://drive.google.com/file/d/1paL0q-GxVTBMeGTe8UqhiBt2b3iH4_b7/view?usp=drive_link",
  " https://drive.google.com/file/d/1I56ofmolVJyyI9VpA-ugSHOnyTQwHVub/view?usp=drive_link",
  " https://drive.google.com/file/d/1MnHe0NPPQ9EH27QOSGwp22_Qxk6VmACm/view?usp=drive_link",
  " https://drive.google.com/file/d/16UjbboKS1f8qk5nvAmCgoZhXs63wDya7/view?usp=drive_link",
  " https://drive.google.com/file/d/1DKCptJ5Ny4spgz-3T4LiG6pXZUfOESZA/view?usp=drive_link",
  " https://drive.google.com/file/d/1rV-u7N9eIT-CGnsmAGDM7kQxejTtAOKa/view?usp=drive_link",
  " https://drive.google.com/file/d/1Msr4O3XpagiG57SxRx0jT39UDOe9i0KP/view?usp=drive_link",
  " https://drive.google.com/file/d/1yaHN-CpUQsR-DALwQBb4i0ueqkN6Ru0Y/view?usp=drive_link",
  " https://drive.google.com/file/d/1gkGkiX63kc-nfbQwnNEChwMfBboy00yu/view?usp=drive_link",
  " https://drive.google.com/file/d/1Y0HUEAPpQ1dqD7DlaUHBlr5B7zilgKGZ/view?usp=drive_link",
  " https://drive.google.com/file/d/1o9vyMm9IM60o-9rTY0kzI__T0hfOsP9D/view?usp=drive_link",
  "https://drive.google.com/file/d/1YEhZbXZgmXvpTNQHcQ4T9xUlRNGekIHI/view?usp=drive_link",
"https://drive.google.com/file/d/1Pf6gZtKBEWN4YlT-13I7C--FCciNBVpK/view?usp=drive_link",
"https://drive.google.com/file/d/1t1nJclGEbv958jwA3jED-9tVbFa7xofB/view?usp=drive_link",
"https://drive.google.com/file/d/1ymPhFVHVfGNB--FIsnPk3ITu7wQPz83L/view?usp=drive_link",
"https://drive.google.com/file/d/1mQJ6UZryEHpDLDePhJv0VpaLWbBiFd2K/view?usp=drive_link",
"https://drive.google.com/file/d/1S_evJfwAYXepwJGjl46xUFGUZ7th-M8V/view?usp=drive_link",
"https://drive.google.com/file/d/1-7KogTzxzCQlqWUWt7WvKrB8CU3mbJpr/view?usp=drive_link",
"https://drive.google.com/file/d/1DBkhp3Sg0Vt9GXOjDHkZJDxKclommESI/view?usp=drive_link",
"https://drive.google.com/file/d/1UON5fFoEd7xlO5091aISqueR7_38SSVu/view?usp=drive_link",
"https://drive.google.com/file/d/1wllAT7cWt8ytyJd6qHV4MayZxR1JcXI3/view?usp=drive_link",
"https://drive.google.com/file/d/10sEm5o8_FBZW3jXeZ2Arvy1dUb7QePLe/view?usp=drive_link",
"https://drive.google.com/file/d/19dNMLTKUEjhf3tIxKxW2DmEqs7Mr7d1t/view?usp=drive_link",
"https://drive.google.com/file/d/1WWRtYtSND5cITKGaM08-tp6P_b_9Mmiy/view?usp=drive_link",
"https://drive.google.com/file/d/1HHtU-x4PWatrFFKy_WAZVg3gJn0tFy63/view?usp=drive_link",
"https://drive.google.com/file/d/1ppC_-SiygULAIXCS5IbH4iaf0XrkZQGG/view?usp=drive_link",
"https://drive.google.com/file/d/1PE6_KqGvfUEB1cQdN4kJVRE5kzGmZf3H/view?usp=drive_link",
"https://drive.google.com/file/d/1usKTfaqpyqbpAfYYX7qcUWOqCCI0zlEp/view?usp=drive_link",
"https://drive.google.com/file/d/1n05wuNsScLYJEQ21uoU8uQqIVi_yVts6/view?usp=drive_link",
"https://drive.google.com/file/d/1xFCPm7iNrbL6853Gim5rk8DghQ9aMqG4/view?usp=drive_link",
"https://drive.google.com/file/d/1dJOnMNFyXgUKFitlEPJFBLT1AdaXptfX/view?usp=drive_link",
"https://drive.google.com/file/d/1jSjn3F7DUfuqRJoi2_vRO25mAA44ZCp9/view?usp=drive_link",
"https://drive.google.com/file/d/1z20Agn9ZsAky3JEe9mjdxCqeP6rn5DTG/view?usp=drive_link",
"https://drive.google.com/file/d/1EQxAJP1nXAhyas7LFQrUSoyOBdo-A73e/view?usp=drive_link",
"https://drive.google.com/file/d/1Tep-FP7v-aSkfF796wDFSGzw6Q8dnjkc/view?usp=drive_link",
"https://drive.google.com/file/d/1te3da-24ehrcPUwzdp2DmyoO2vyewoVy/view?usp=drive_link",
"https://drive.google.com/file/d/115SAZlAhzrn19PqBwixuoRxvHvXmdBr7/view?usp=drive_link",
"https://drive.google.com/file/d/1lo6BzlV90qz0iEk1vnE1njHwYU44MwU8/view?usp=drive_link",
"https://drive.google.com/file/d/1hfLah50gOK1DG2o47r4pwRars5LUyCar/view?usp=drive_link",
"https://drive.google.com/file/d/1KsTwBGTBBHUt_HnSc1DzTgGFfYAsDTLw/view?usp=drive_link",
"https://drive.google.com/file/d/1QoPzIPKiUr5a3wt0FY51-TMWf7nt2Au6/view?usp=drive_link",
"https://drive.google.com/file/d/1AF4KxKC5d89S0JDPm3zc6chlj4EDaAJX/view?usp=drive_link",
"https://drive.google.com/file/d/1AeTL4STK0q2T2dZAkCTnbSZr-SVYA-4b/view?usp=drive_link",
"https://drive.google.com/file/d/1WxtkXoJA8vE7Xx1g-tHjC0yfZg0jef_T/view?usp=drive_link",
"https://drive.google.com/file/d/1Y0InjmAXhKvpGnbZctFouKcfdN9vdk5_/view?usp=drive_link",
"https://drive.google.com/file/d/1GUpACWmUdTGvPUNOwZ4wvj-QHc_l5wA2/view?usp=drive_link",
"https://drive.google.com/file/d/1uhPYf9ou1mhy0WXnrsjtNB_OY4tkqNCz/view?usp=drive_link",
"https://drive.google.com/file/d/1CYG5sPEVxW8S_NTD4Lj4b_7UdU0TccVo/view?usp=drive_link",
"https://drive.google.com/file/d/1f_kXTxGsC0WxjUaIeFF8sv51SLQP3zDx/view?usp=drive_link",
"https://drive.google.com/file/d/1ypxOn2rc-aa1ZkpU-keD_N142JmbKwqs/view?usp=drive_link",
"https://drive.google.com/file/d/1ZsIADc-kwi0b7M-Ba4zVY2kRIj_OiHpH/view?usp=drive_link",
"https://drive.google.com/file/d/1dY0mbuYyBzzrfj8t0L4hzVL-NOAzyU_G/view?usp=drive_link",
"https://drive.google.com/file/d/17bMvzsM2-4YLYqP3ZlErcAOn46zNoFro/view?usp=drive_link",
"https://drive.google.com/file/d/1y3nD2yL6ZZ_jO8qRStXLAbnnV9DkiMrq/view?usp=drive_link",
"https://drive.google.com/file/d/126ThkwPkcamwRY5v4-212v_BeIadZy46/view?usp=drive_link",
"https://drive.google.com/file/d/1dOv7PVA0CxJO_Hc_hwMyf8WUbVUv4qhR/view?usp=drive_link",
"https://drive.google.com/file/d/1x6JOGxAJJfr7X4rqGFEi4pwFTIxMIWzi/view?usp=drive_link",
"https://drive.google.com/file/d/1MQBLsbinZu3euMXa_JRxmZfEd_nOp3AB/view?usp=drive_link",
"https://drive.google.com/file/d/1wcMqAA9yWAW5Ge9PWh3Y0Q9K6Tkp7OA0/view?usp=drive_link",
"https://drive.google.com/file/d/1PAMWz8CP8zgvnDtCZJ7qfcttBh3UTUis/view?usp=drive_link",
"https://drive.google.com/file/d/1k8z4A_x2zriVNbL2H_y7ol4i7SsxA9LH/view?usp=drive_link",
"https://drive.google.com/file/d/1o5KdQSBFKOb3p4giBlQUx1idKOQELnHW/view?usp=drive_link",
"https://drive.google.com/file/d/1dqCnbli1W3p041kroLmuGQ-i27dngkW9/view?usp=drive_link",
"https://drive.google.com/file/d/11y44IzhdIVP-fIsThOccMlcBbR1ed6it/view?usp=drive_link",
"https://drive.google.com/file/d/1BkS8uJktkBheACvt42N0HIbYgTXhJP28/view?usp=drive_link",
"https://drive.google.com/file/d/1QuTCy25nuOGbG11fWT_zNGPkIyRVAx9P/view?usp=drive_link",
"https://drive.google.com/file/d/1_QjG6PspE3jA-eBKBjrQ-eRrAm4B5EAm/view?usp=drive_link",
"https://drive.google.com/file/d/1c9SUtSYCuwbEPonC4TYtI3e3Ap2HR091/view?usp=drive_link",
"https://drive.google.com/file/d/14DOneL-vSv_pyH6aRHQBaNsW498S8moZ/view?usp=drive_link",
"https://drive.google.com/file/d/1Z3z_NpqxAksTN-T10PX2fxc81DPClNqW/view?usp=drive_link",
"https://drive.google.com/file/d/1ThDnKrANB8A_h0aG4zfRsqOBnbg-Y3hT/view?usp=drive_link",
"https://drive.google.com/file/d/1WvKaO51FzTRxe-MuuDx1C94XNYmAIujc/view?usp=drive_link",
"https://drive.google.com/file/d/1MeKxP4W6qvSfGTvIZoRgoxNUBP7ZwAZU/view?usp=drive_link",
"https://drive.google.com/file/d/1G_hdLUZYPwyjjner0n3GLNTjvpI5ouhz/view?usp=drive_link",
"https://drive.google.com/file/d/1GbAC1CY6fgRfr2KuHFSWLJGuVfyceI54/view?usp=drive_link",
"https://drive.google.com/file/d/1MvKd-qJ_mMo-Epna5JOJCeZaPrducTW_/view?usp=drive_link",
"https://drive.google.com/file/d/1GCFlq-C4Vn5bSo9ybUQwl0k6q3fmvRG3/view?usp=drive_link",
"https://drive.google.com/file/d/1qHekvbE7GCvS-Zf9RcQlZn0W2H_WZGi1/view?usp=drive_link",
"https://drive.google.com/file/d/16qK4fbjXOzce73JPxtJkrdTv0d7dYzAM/view?usp=drive_link",
"https://drive.google.com/file/d/1X3rida1xl0uIEthuBJOHDHICXbK7K7Zx/view?usp=drive_link",
"https://drive.google.com/file/d/1xyfdHOX5DqJFIScWqXB1JL9zBj8g5_Ag/view?usp=drive_link"

]

// const title =[
// "models"
// ]

// const linkd=document.getElementById("container");
// link.forEach((link,index)=>{
// const div=document.createElement("div");
// div.className("models");
// const title= titles[index] || `${index+1}`
// div.innerHTML= `<a href=${link} > ${title} </a> `
// linkd=document.appendChild(div);

// }
// );


const titles = [
"Idiom and Phrases",
"Aman Sir English Class Notes",
"Vocabulary Book"
];

const container = document.getElementById("ebookcontainer");

link.forEach((link, index) => {
    const div = document.createElement("div");
    div.className = "item";
    const title = titles[index] || `Ebook ${index + 1}`;

div.innerHTML = `<a href="${link}" target="_blank">${title}</a> `;
container.appendChild(div);
});
